export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const FETCH_TODOS_RESPONSE = 'FETCH_TODOS_RESPONSE'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const TOGGLE_INPUT = 'TOGGLE_INPUT'

export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST'
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS'

export const TOGGLE_TODO_VALIDITY = 'TOGGLE_TODO_VALIDITY'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_ACTIVE = 'SHOW_ACTIVE'
export const SHOW_COMPLETED = 'SHOW_COMPLETED'
